spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:h2:mem:pedido-facil
    username: sa
    password: ~
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    loggers: slf4j
