spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:educa-facil}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:password}
  flyway:
    loggers: slf4j
    enabled: ${USE_FLYWAY:false}
